package maa

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// Role and coordination markers for the server child invocation of this test
// binary. The parent keeps its own process free of agent-server state; the
// child owns the server singleton and exits after the client disconnects.
const (
	agentClientTcpRoleEnv  = "MAA_AGENT_CLIENT_TCP_TEST_ROLE"
	agentClientTcpPortEnv  = "MAA_AGENT_CLIENT_TCP_TEST_PORT"
	agentClientTcpReadyEnv = "MAA_AGENT_CLIENT_TCP_TEST_READY"

	agentClientTcpRoleServer = "server"

	agentClientTcpReadyWait = 10 * time.Second
	agentClientTcpExitWait  = 10 * time.Second
	agentClientTcpKillWait  = 5 * time.Second
	agentClientTcpPollEvery = 20 * time.Millisecond
)

// TestAgentClient_IdentifierAutoGenerated pins that an empty identifier makes
// the native layer generate a non-empty identifier for the client.
func TestAgentClient_IdentifierAutoGenerated(t *testing.T) {
	client, err := NewAgentClient(WithIdentifier(""))
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, client.Destroy()) })

	identifier, err := client.Identifier()
	require.NoError(t, err)
	require.NotEmpty(t, identifier, "empty identifier must be auto-generated")
}

// TestAgentClient_IdentifierExplicit pins that a non-empty identifier is
// preserved verbatim by the native client.
func TestAgentClient_IdentifierExplicit(t *testing.T) {
	const fixed = "maa-go-e2e-fixed-id"
	client, err := NewAgentClient(WithIdentifier(fixed))
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, client.Destroy()) })

	identifier, err := client.Identifier()
	require.NoError(t, err)
	require.Equal(t, fixed, identifier)
}

// TestAgentClient_TcpPortIdentifierAndPairing pins the TCP creation mode end to
// end. The parent creates a TCP client on an OS-selected port and checks that
// Identifier reports that port as a numeric string; a child process then starts
// a real Agent Server on exactly that port, and the parent connects, probes,
// and disconnects against it. The parent never touches agent-server APIs, so
// the server singleton lives only in the child.
func TestAgentClient_TcpPortIdentifierAndPairing(t *testing.T) {
	if os.Getenv(agentClientTcpRoleEnv) == agentClientTcpRoleServer {
		runAgentClientTcpServerHelper(t)
		return
	}

	client, err := NewAgentClient(WithTcpPort(0))
	require.NoError(t, err)
	portIdentifier, err := client.Identifier()
	require.NoError(t, err)
	port, err := strconv.Atoi(portIdentifier)
	require.NoError(t, err, "TCP client identifier must be the numeric port, got %q", portIdentifier)
	require.Greater(t, port, 0, "port 0 must be replaced by the OS-selected port")

	dir := t.TempDir()
	readyPath := filepath.Join(dir, "server-ready")
	logPath := filepath.Join(dir, "server.log")
	server := startAgentClientTcpServer(t, portIdentifier, readyPath, logPath)

	waitAgentClientTcpReady(t, readyPath, server, logPath)

	connected := false
	var res *Resource
	t.Cleanup(func() {
		if connected {
			_ = client.Disconnect()
		}
		require.NoError(t, client.Destroy())
		if res != nil {
			require.NoError(t, res.Destroy())
		}
	})

	require.NoError(t, client.SetTimeout(5*time.Second))
	res, err = NewResource()
	require.NoError(t, err)
	require.NoError(t, client.BindResource(res))
	require.NoError(t, client.Connect(), "connect failed; server log:\n%s", readAgentClientTcpLog(logPath))
	connected = true
	require.True(t, client.Connected())
	require.True(t, client.Alive())

	require.NoError(t, client.Disconnect())
	connected = false
	require.NoError(t, client.Destroy())
	require.NoError(t, res.Destroy())
	res = nil

	// Join in the child returns once the client disconnects, so the child must
	// exit cleanly after finishing its own shutdown sequence.
	waitErr := server.wait(t, logPath)
	require.NoError(t, waitErr, "agent server child failed; log:\n%s", readAgentClientTcpLog(logPath))
}

// runAgentClientTcpServerHelper starts a real Agent Server bound to the given
// TCP port inside the child process. TestMain has already initialized the
// framework. Join blocks until the paired client disconnects; the subsequent
// ShutDown lets the child exit cleanly.
func runAgentClientTcpServerHelper(t *testing.T) {
	t.Helper()

	port := os.Getenv(agentClientTcpPortEnv)
	readyPath := os.Getenv(agentClientTcpReadyEnv)
	require.NotEmpty(t, port)
	require.NotEmpty(t, readyPath)

	require.NoError(t, AgentServerStartUp(port))
	require.NoError(t, os.WriteFile(readyPath, []byte("ready"), 0o600))
	AgentServerJoin()
	AgentServerShutDown()
}

// agentClientTcpServer tracks the child server process, its exit state, and
// its log path. Every receive from done must go through recordExit so later
// checks see a consistent exit state.
type agentClientTcpServer struct {
	logPath string
	cmd     *exec.Cmd
	done    chan error
	exited  bool
	exitErr error
}

func startAgentClientTcpServer(t *testing.T, port, readyPath, logPath string) *agentClientTcpServer {
	t.Helper()

	logFile, err := os.Create(logPath)
	require.NoError(t, err)

	cmd := exec.Command(os.Args[0],
		"-test.run=^TestAgentClient_TcpPortIdentifierAndPairing$",
		"-test.count=1",
		"-test.v",
	)
	cmd.Env = append(os.Environ(),
		agentClientTcpRoleEnv+"="+agentClientTcpRoleServer,
		agentClientTcpPortEnv+"="+port,
		agentClientTcpReadyEnv+"="+readyPath,
	)
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	require.NoError(t, cmd.Start())
	require.NoError(t, logFile.Close())

	server := &agentClientTcpServer{logPath: logPath, cmd: cmd, done: make(chan error, 1)}
	go func() { server.done <- cmd.Wait() }()
	t.Cleanup(func() {
		if server.killAndReap() {
			return
		}
		t.Error("agent server child did not exit after kill")
	})
	return server
}

func (s *agentClientTcpServer) recordExit(err error) {
	s.exited = true
	s.exitErr = err
}

// pollExit reports whether the child has exited, draining a wait result that
// is already available.
func (s *agentClientTcpServer) pollExit() bool {
	if !s.exited {
		select {
		case err := <-s.done:
			s.recordExit(err)
		default:
		}
	}
	return s.exited
}

// wait blocks until the child exits or the deadline expires, returning the
// child's wait error or a timeout error.
func (s *agentClientTcpServer) wait(t *testing.T, logPath string) error {
	t.Helper()

	if s.pollExit() {
		return s.exitErr
	}
	select {
	case err := <-s.done:
		s.recordExit(err)
		return err
	case <-time.After(agentClientTcpExitWait):
		return errors.New("agent server child did not exit after disconnect; log:\n" + readAgentClientTcpLog(logPath))
	}
}

func (s *agentClientTcpServer) killAndReap() bool {
	if s.pollExit() {
		return true
	}
	if err := s.cmd.Process.Kill(); err != nil && !errors.Is(err, os.ErrProcessDone) {
		return false
	}
	select {
	case err := <-s.done:
		s.recordExit(err)
		return true
	case <-time.After(agentClientTcpKillWait):
		return false
	}
}

// waitAgentClientTcpReady polls for the child's ready file, failing early when
// the child exits before the server came up.
func waitAgentClientTcpReady(t *testing.T, readyPath string, server *agentClientTcpServer, logPath string) {
	t.Helper()

	deadline := time.NewTimer(agentClientTcpReadyWait)
	defer deadline.Stop()
	tick := time.NewTicker(agentClientTcpPollEvery)
	defer tick.Stop()
	for {
		if _, err := os.Stat(readyPath); err == nil {
			return
		}
		select {
		case err := <-server.done:
			server.recordExit(err)
			t.Fatalf("agent server child exited before becoming ready: %v\n%s", err, readAgentClientTcpLog(logPath))
		case <-deadline.C:
			t.Fatalf("timed out waiting for the agent server child; log:\n%s", readAgentClientTcpLog(logPath))
		case <-tick.C:
		}
	}
}

func readAgentClientTcpLog(path string) string {
	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err.Error()
	}
	return string(data)
}
