// Code generated by go generate; DO NOT EDIT.

package maa

type TaskerEventSink interface {
	OnResourceLoading(tasker *Tasker, event EventStatus, detail ResourceLoadingDetail)
	OnControllerAction(tasker *Tasker, event EventStatus, detail ControllerActionDetail)
	OnTaskerTask(tasker *Tasker, event EventStatus, detail TaskerTaskDetail)
	OnNodePipelineNode(tasker *Tasker, event EventStatus, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(tasker *Tasker, event EventStatus, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(tasker *Tasker, event EventStatus, detail NodeActionNodeDetail)
	OnTaskNextList(tasker *Tasker, event EventStatus, detail NodeNextListDetail)
	OnTaskRecognition(tasker *Tasker, event EventStatus, detail NodeRecognitionDetail)
	OnTaskAction(tasker *Tasker, event EventStatus, detail NodeActionDetail)
	OnUnknownEvent(tasker *Tasker, msg, detailsJSON string)
}

// TaskerEventSinkAdapter is a lightweight adapter that makes it easy to register
// a single-event handler via a callback function.
type TaskerEventSinkAdapter struct {
	onResourceLoading     func(EventStatus, ResourceLoadingDetail)
	onControllerAction    func(EventStatus, ControllerActionDetail)
	onTaskerTask          func(EventStatus, TaskerTaskDetail)
	onNodePipelineNode    func(EventStatus, NodePipelineNodeDetail)
	onNodeRecognitionNode func(EventStatus, NodeRecognitionNodeDetail)
	onNodeActionNode      func(EventStatus, NodeActionNodeDetail)
	onTaskNextList        func(EventStatus, NodeNextListDetail)
	onTaskRecognition     func(EventStatus, NodeRecognitionDetail)
	onTaskAction          func(EventStatus, NodeActionDetail)
	onUnknownEvent        func(string, string)
}

func (a *TaskerEventSinkAdapter) OnResourceLoading(tasker *Tasker, status EventStatus, detail ResourceLoadingDetail) {
	if a == nil || a.onResourceLoading == nil {
		return
	}
	a.onResourceLoading(status, detail)
}

func (a *TaskerEventSinkAdapter) OnControllerAction(tasker *Tasker, status EventStatus, detail ControllerActionDetail) {
	if a == nil || a.onControllerAction == nil {
		return
	}
	a.onControllerAction(status, detail)
}

func (a *TaskerEventSinkAdapter) OnTaskerTask(tasker *Tasker, status EventStatus, detail TaskerTaskDetail) {
	if a == nil || a.onTaskerTask == nil {
		return
	}
	a.onTaskerTask(status, detail)
}

func (a *TaskerEventSinkAdapter) OnNodePipelineNode(tasker *Tasker, status EventStatus, detail NodePipelineNodeDetail) {
	if a == nil || a.onNodePipelineNode == nil {
		return
	}
	a.onNodePipelineNode(status, detail)
}

func (a *TaskerEventSinkAdapter) OnNodeRecognitionNode(tasker *Tasker, status EventStatus, detail NodeRecognitionNodeDetail) {
	if a == nil || a.onNodeRecognitionNode == nil {
		return
	}
	a.onNodeRecognitionNode(status, detail)
}

func (a *TaskerEventSinkAdapter) OnNodeActionNode(tasker *Tasker, status EventStatus, detail NodeActionNodeDetail) {
	if a == nil || a.onNodeActionNode == nil {
		return
	}
	a.onNodeActionNode(status, detail)
}

func (a *TaskerEventSinkAdapter) OnTaskNextList(tasker *Tasker, status EventStatus, detail NodeNextListDetail) {
	if a == nil || a.onTaskNextList == nil {
		return
	}
	a.onTaskNextList(status, detail)
}

func (a *TaskerEventSinkAdapter) OnTaskRecognition(tasker *Tasker, status EventStatus, detail NodeRecognitionDetail) {
	if a == nil || a.onTaskRecognition == nil {
		return
	}
	a.onTaskRecognition(status, detail)
}

func (a *TaskerEventSinkAdapter) OnTaskAction(tasker *Tasker, status EventStatus, detail NodeActionDetail) {
	if a == nil || a.onTaskAction == nil {
		return
	}
	a.onTaskAction(status, detail)
}

func (a *TaskerEventSinkAdapter) OnUnknownEvent(tasker *Tasker, msg, detailsJSON string) {
	if a == nil || a.onUnknownEvent == nil {
		return
	}
	a.onUnknownEvent(msg, detailsJSON)
}

// OnResourceLoading registers a callback sink that only handles Resource.Loading events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnResourceLoading(fn func(EventStatus, ResourceLoadingDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onResourceLoading: fn}
	return t.AddSink(sink)
}

// OnControllerAction registers a callback sink that only handles Controller.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnControllerAction(fn func(EventStatus, ControllerActionDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onControllerAction: fn}
	return t.AddSink(sink)
}

// OnTaskerTask registers a callback sink that only handles Tasker.Task events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskerTask(fn func(EventStatus, TaskerTaskDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onTaskerTask: fn}
	return t.AddSink(sink)
}

// OnNodePipelineNode registers a callback sink that only handles Node.PipelineNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodePipelineNode(fn func(EventStatus, NodePipelineNodeDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onNodePipelineNode: fn}
	return t.AddSink(sink)
}

// OnNodeRecognitionNode registers a callback sink that only handles Node.RecognitionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodeRecognitionNode(fn func(EventStatus, NodeRecognitionNodeDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onNodeRecognitionNode: fn}
	return t.AddSink(sink)
}

// OnNodeActionNode registers a callback sink that only handles Node.ActionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodeActionNode(fn func(EventStatus, NodeActionNodeDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onNodeActionNode: fn}
	return t.AddSink(sink)
}

// OnTaskNextList registers a callback sink that only handles Node.NextList events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskNextList(fn func(EventStatus, NodeNextListDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onTaskNextList: fn}
	return t.AddSink(sink)
}

// OnTaskRecognition registers a callback sink that only handles Node.Recognition events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskRecognition(fn func(EventStatus, NodeRecognitionDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onTaskRecognition: fn}
	return t.AddSink(sink)
}

// OnTaskAction registers a callback sink that only handles Node.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskAction(fn func(EventStatus, NodeActionDetail)) int64 {
	sink := &TaskerEventSinkAdapter{onTaskAction: fn}
	return t.AddSink(sink)
}

// OnUnknownEvent registers a callback sink that only handles unknown events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnUnknownEvent(fn func(msg, detailsJSON string)) int64 {
	sink := &TaskerEventSinkAdapter{onUnknownEvent: fn}
	return t.AddSink(sink)
}

type ResourceEventSink interface {
	OnResourceLoading(res *Resource, event EventStatus, detail ResourceLoadingDetail)
	OnControllerAction(res *Resource, event EventStatus, detail ControllerActionDetail)
	OnTaskerTask(res *Resource, event EventStatus, detail TaskerTaskDetail)
	OnNodePipelineNode(res *Resource, event EventStatus, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(res *Resource, event EventStatus, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(res *Resource, event EventStatus, detail NodeActionNodeDetail)
	OnTaskNextList(res *Resource, event EventStatus, detail NodeNextListDetail)
	OnTaskRecognition(res *Resource, event EventStatus, detail NodeRecognitionDetail)
	OnTaskAction(res *Resource, event EventStatus, detail NodeActionDetail)
	OnUnknownEvent(res *Resource, msg, detailsJSON string)
}

// ResourceEventSinkAdapter is a lightweight adapter that makes it easy to register
// a single-event handler via a callback function.
type ResourceEventSinkAdapter struct {
	onResourceLoading     func(EventStatus, ResourceLoadingDetail)
	onControllerAction    func(EventStatus, ControllerActionDetail)
	onTaskerTask          func(EventStatus, TaskerTaskDetail)
	onNodePipelineNode    func(EventStatus, NodePipelineNodeDetail)
	onNodeRecognitionNode func(EventStatus, NodeRecognitionNodeDetail)
	onNodeActionNode      func(EventStatus, NodeActionNodeDetail)
	onTaskNextList        func(EventStatus, NodeNextListDetail)
	onTaskRecognition     func(EventStatus, NodeRecognitionDetail)
	onTaskAction          func(EventStatus, NodeActionDetail)
	onUnknownEvent        func(string, string)
}

func (a *ResourceEventSinkAdapter) OnResourceLoading(res *Resource, status EventStatus, detail ResourceLoadingDetail) {
	if a == nil || a.onResourceLoading == nil {
		return
	}
	a.onResourceLoading(status, detail)
}

func (a *ResourceEventSinkAdapter) OnControllerAction(res *Resource, status EventStatus, detail ControllerActionDetail) {
	if a == nil || a.onControllerAction == nil {
		return
	}
	a.onControllerAction(status, detail)
}

func (a *ResourceEventSinkAdapter) OnTaskerTask(res *Resource, status EventStatus, detail TaskerTaskDetail) {
	if a == nil || a.onTaskerTask == nil {
		return
	}
	a.onTaskerTask(status, detail)
}

func (a *ResourceEventSinkAdapter) OnNodePipelineNode(res *Resource, status EventStatus, detail NodePipelineNodeDetail) {
	if a == nil || a.onNodePipelineNode == nil {
		return
	}
	a.onNodePipelineNode(status, detail)
}

func (a *ResourceEventSinkAdapter) OnNodeRecognitionNode(res *Resource, status EventStatus, detail NodeRecognitionNodeDetail) {
	if a == nil || a.onNodeRecognitionNode == nil {
		return
	}
	a.onNodeRecognitionNode(status, detail)
}

func (a *ResourceEventSinkAdapter) OnNodeActionNode(res *Resource, status EventStatus, detail NodeActionNodeDetail) {
	if a == nil || a.onNodeActionNode == nil {
		return
	}
	a.onNodeActionNode(status, detail)
}

func (a *ResourceEventSinkAdapter) OnTaskNextList(res *Resource, status EventStatus, detail NodeNextListDetail) {
	if a == nil || a.onTaskNextList == nil {
		return
	}
	a.onTaskNextList(status, detail)
}

func (a *ResourceEventSinkAdapter) OnTaskRecognition(res *Resource, status EventStatus, detail NodeRecognitionDetail) {
	if a == nil || a.onTaskRecognition == nil {
		return
	}
	a.onTaskRecognition(status, detail)
}

func (a *ResourceEventSinkAdapter) OnTaskAction(res *Resource, status EventStatus, detail NodeActionDetail) {
	if a == nil || a.onTaskAction == nil {
		return
	}
	a.onTaskAction(status, detail)
}

func (a *ResourceEventSinkAdapter) OnUnknownEvent(res *Resource, msg, detailsJSON string) {
	if a == nil || a.onUnknownEvent == nil {
		return
	}
	a.onUnknownEvent(msg, detailsJSON)
}

// OnResourceLoading registers a callback sink that only handles Resource.Loading events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnResourceLoading(fn func(EventStatus, ResourceLoadingDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onResourceLoading: fn}
	return r.AddSink(sink)
}

// OnControllerAction registers a callback sink that only handles Controller.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnControllerAction(fn func(EventStatus, ControllerActionDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onControllerAction: fn}
	return r.AddSink(sink)
}

// OnTaskerTask registers a callback sink that only handles Tasker.Task events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnTaskerTask(fn func(EventStatus, TaskerTaskDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onTaskerTask: fn}
	return r.AddSink(sink)
}

// OnNodePipelineNode registers a callback sink that only handles Node.PipelineNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnNodePipelineNode(fn func(EventStatus, NodePipelineNodeDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onNodePipelineNode: fn}
	return r.AddSink(sink)
}

// OnNodeRecognitionNode registers a callback sink that only handles Node.RecognitionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnNodeRecognitionNode(fn func(EventStatus, NodeRecognitionNodeDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onNodeRecognitionNode: fn}
	return r.AddSink(sink)
}

// OnNodeActionNode registers a callback sink that only handles Node.ActionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnNodeActionNode(fn func(EventStatus, NodeActionNodeDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onNodeActionNode: fn}
	return r.AddSink(sink)
}

// OnTaskNextList registers a callback sink that only handles Node.NextList events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnTaskNextList(fn func(EventStatus, NodeNextListDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onTaskNextList: fn}
	return r.AddSink(sink)
}

// OnTaskRecognition registers a callback sink that only handles Node.Recognition events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnTaskRecognition(fn func(EventStatus, NodeRecognitionDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onTaskRecognition: fn}
	return r.AddSink(sink)
}

// OnTaskAction registers a callback sink that only handles Node.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnTaskAction(fn func(EventStatus, NodeActionDetail)) int64 {
	sink := &ResourceEventSinkAdapter{onTaskAction: fn}
	return r.AddSink(sink)
}

// OnUnknownEvent registers a callback sink that only handles unknown events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (r *Resource) OnUnknownEvent(fn func(msg, detailsJSON string)) int64 {
	sink := &ResourceEventSinkAdapter{onUnknownEvent: fn}
	return r.AddSink(sink)
}

type ContextEventSink interface {
	OnResourceLoading(ctx *Context, event EventStatus, detail ResourceLoadingDetail)
	OnControllerAction(ctx *Context, event EventStatus, detail ControllerActionDetail)
	OnTaskerTask(ctx *Context, event EventStatus, detail TaskerTaskDetail)
	OnNodePipelineNode(ctx *Context, event EventStatus, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(ctx *Context, event EventStatus, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(ctx *Context, event EventStatus, detail NodeActionNodeDetail)
	OnTaskNextList(ctx *Context, event EventStatus, detail NodeNextListDetail)
	OnTaskRecognition(ctx *Context, event EventStatus, detail NodeRecognitionDetail)
	OnTaskAction(ctx *Context, event EventStatus, detail NodeActionDetail)
	OnUnknownEvent(ctx *Context, msg, detailsJSON string)
}

// ContextEventSinkAdapter is a lightweight adapter that makes it easy to register
// a single-event handler via a callback function.
type ContextEventSinkAdapter struct {
	onResourceLoading     func(*Context, EventStatus, ResourceLoadingDetail)
	onControllerAction    func(*Context, EventStatus, ControllerActionDetail)
	onTaskerTask          func(*Context, EventStatus, TaskerTaskDetail)
	onNodePipelineNode    func(*Context, EventStatus, NodePipelineNodeDetail)
	onNodeRecognitionNode func(*Context, EventStatus, NodeRecognitionNodeDetail)
	onNodeActionNode      func(*Context, EventStatus, NodeActionNodeDetail)
	onTaskNextList        func(*Context, EventStatus, NodeNextListDetail)
	onTaskRecognition     func(*Context, EventStatus, NodeRecognitionDetail)
	onTaskAction          func(*Context, EventStatus, NodeActionDetail)
	onUnknownEvent        func(*Context, string, string)
}

func (a *ContextEventSinkAdapter) OnResourceLoading(ctx *Context, status EventStatus, detail ResourceLoadingDetail) {
	if a == nil || a.onResourceLoading == nil {
		return
	}
	a.onResourceLoading(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnControllerAction(ctx *Context, status EventStatus, detail ControllerActionDetail) {
	if a == nil || a.onControllerAction == nil {
		return
	}
	a.onControllerAction(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnTaskerTask(ctx *Context, status EventStatus, detail TaskerTaskDetail) {
	if a == nil || a.onTaskerTask == nil {
		return
	}
	a.onTaskerTask(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnNodePipelineNode(ctx *Context, status EventStatus, detail NodePipelineNodeDetail) {
	if a == nil || a.onNodePipelineNode == nil {
		return
	}
	a.onNodePipelineNode(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnNodeRecognitionNode(ctx *Context, status EventStatus, detail NodeRecognitionNodeDetail) {
	if a == nil || a.onNodeRecognitionNode == nil {
		return
	}
	a.onNodeRecognitionNode(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnNodeActionNode(ctx *Context, status EventStatus, detail NodeActionNodeDetail) {
	if a == nil || a.onNodeActionNode == nil {
		return
	}
	a.onNodeActionNode(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnTaskNextList(ctx *Context, status EventStatus, detail NodeNextListDetail) {
	if a == nil || a.onTaskNextList == nil {
		return
	}
	a.onTaskNextList(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnTaskRecognition(ctx *Context, status EventStatus, detail NodeRecognitionDetail) {
	if a == nil || a.onTaskRecognition == nil {
		return
	}
	a.onTaskRecognition(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnTaskAction(ctx *Context, status EventStatus, detail NodeActionDetail) {
	if a == nil || a.onTaskAction == nil {
		return
	}
	a.onTaskAction(ctx, status, detail)
}

func (a *ContextEventSinkAdapter) OnUnknownEvent(ctx *Context, msg, detailsJSON string) {
	if a == nil || a.onUnknownEvent == nil {
		return
	}
	a.onUnknownEvent(ctx, msg, detailsJSON)
}

// OnResourceLoadingInContext  registers a callback sink that only handles Resource.Loading events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnResourceLoadingInContext(fn func(*Context, EventStatus, ResourceLoadingDetail)) int64 {
	sink := &ContextEventSinkAdapter{onResourceLoading: fn}
	return t.AddContextSink(sink)
}

// OnControllerActionInContext registers a callback sink that only handles Controller.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnControllerActionInContext(fn func(*Context, EventStatus, ControllerActionDetail)) int64 {
	sink := &ContextEventSinkAdapter{onControllerAction: fn}
	return t.AddContextSink(sink)
}

// OnTaskerTaskInContext  registers a callback sink that only handles Tasker.Task events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskerTaskInContext(fn func(*Context, EventStatus, TaskerTaskDetail)) int64 {
	sink := &ContextEventSinkAdapter{onTaskerTask: fn}
	return t.AddContextSink(sink)
}

// OnNodePipelineNodeInContext registers a callback sink that only handles Node.PipelineNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodePipelineNodeInContext(fn func(*Context, EventStatus, NodePipelineNodeDetail)) int64 {
	sink := &ContextEventSinkAdapter{onNodePipelineNode: fn}
	return t.AddContextSink(sink)
}

// OnNodeRecognitionNodeInContext registers a callback sink that only handles Node.RecognitionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodeRecognitionNodeInContext(fn func(*Context, EventStatus, NodeRecognitionNodeDetail)) int64 {
	sink := &ContextEventSinkAdapter{onNodeRecognitionNode: fn}
	return t.AddContextSink(sink)
}

// OnNodeActionNodeInContext registers a callback sink that only handles Node.ActionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnNodeActionNodeInContext(fn func(*Context, EventStatus, NodeActionNodeDetail)) int64 {
	sink := &ContextEventSinkAdapter{onNodeActionNode: fn}
	return t.AddContextSink(sink)
}

// OnTaskNextListInContext registers a callback sink that only handles Node.NextList events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskNextListInContext(fn func(*Context, EventStatus, NodeNextListDetail)) int64 {
	sink := &ContextEventSinkAdapter{onTaskNextList: fn}
	return t.AddContextSink(sink)
}

// OnTaskRecognitionInContext registers a callback sink that only handles Node.Recognition events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskRecognitionInContext(fn func(*Context, EventStatus, NodeRecognitionDetail)) int64 {
	sink := &ContextEventSinkAdapter{onTaskRecognition: fn}
	return t.AddContextSink(sink)
}

// OnTaskActionInContext registers a callback sink that only handles Node.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnTaskActionInContext(fn func(*Context, EventStatus, NodeActionDetail)) int64 {
	sink := &ContextEventSinkAdapter{onTaskAction: fn}
	return t.AddContextSink(sink)
}

// OnUnknownEventInContext registers a callback sink that only handles unknown events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (t *Tasker) OnUnknownEventInContext(fn func(ctx *Context, msg, detailsJSON string)) int64 {
	sink := &ContextEventSinkAdapter{onUnknownEvent: fn}
	return t.AddContextSink(sink)
}

type ControllerEventSink interface {
	OnResourceLoading(ctrl *Controller, event EventStatus, detail ResourceLoadingDetail)
	OnControllerAction(ctrl *Controller, event EventStatus, detail ControllerActionDetail)
	OnTaskerTask(ctrl *Controller, event EventStatus, detail TaskerTaskDetail)
	OnNodePipelineNode(ctrl *Controller, event EventStatus, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(ctrl *Controller, event EventStatus, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(ctrl *Controller, event EventStatus, detail NodeActionNodeDetail)
	OnTaskNextList(ctrl *Controller, event EventStatus, detail NodeNextListDetail)
	OnTaskRecognition(ctrl *Controller, event EventStatus, detail NodeRecognitionDetail)
	OnTaskAction(ctrl *Controller, event EventStatus, detail NodeActionDetail)
	OnUnknownEvent(ctrl *Controller, msg, detailsJSON string)
}

// ControllerEventSinkAdapter is a lightweight adapter that makes it easy to register
// a single-event handler via a callback function.
type ControllerEventSinkAdapter struct {
	onResourceLoading     func(EventStatus, ResourceLoadingDetail)
	onControllerAction    func(EventStatus, ControllerActionDetail)
	onTaskerTask          func(EventStatus, TaskerTaskDetail)
	onNodePipelineNode    func(EventStatus, NodePipelineNodeDetail)
	onNodeRecognitionNode func(EventStatus, NodeRecognitionNodeDetail)
	onNodeActionNode      func(EventStatus, NodeActionNodeDetail)
	onTaskNextList        func(EventStatus, NodeNextListDetail)
	onTaskRecognition     func(EventStatus, NodeRecognitionDetail)
	onTaskAction          func(EventStatus, NodeActionDetail)
	onUnknownEvent        func(string, string)
}

func (a *ControllerEventSinkAdapter) OnResourceLoading(ctrl *Controller, status EventStatus, detail ResourceLoadingDetail) {
	if a == nil || a.onResourceLoading == nil {
		return
	}
	a.onResourceLoading(status, detail)
}

func (a *ControllerEventSinkAdapter) OnControllerAction(ctrl *Controller, status EventStatus, detail ControllerActionDetail) {
	if a == nil || a.onControllerAction == nil {
		return
	}
	a.onControllerAction(status, detail)
}

func (a *ControllerEventSinkAdapter) OnTaskerTask(ctrl *Controller, status EventStatus, detail TaskerTaskDetail) {
	if a == nil || a.onTaskerTask == nil {
		return
	}
	a.onTaskerTask(status, detail)
}

func (a *ControllerEventSinkAdapter) OnNodePipelineNode(ctrl *Controller, status EventStatus, detail NodePipelineNodeDetail) {
	if a == nil || a.onNodePipelineNode == nil {
		return
	}
	a.onNodePipelineNode(status, detail)
}

func (a *ControllerEventSinkAdapter) OnNodeRecognitionNode(ctrl *Controller, status EventStatus, detail NodeRecognitionNodeDetail) {
	if a == nil || a.onNodeRecognitionNode == nil {
		return
	}
	a.onNodeRecognitionNode(status, detail)
}

func (a *ControllerEventSinkAdapter) OnNodeActionNode(ctrl *Controller, status EventStatus, detail NodeActionNodeDetail) {
	if a == nil || a.onNodeActionNode == nil {
		return
	}
	a.onNodeActionNode(status, detail)
}

func (a *ControllerEventSinkAdapter) OnTaskNextList(ctrl *Controller, status EventStatus, detail NodeNextListDetail) {
	if a == nil || a.onTaskNextList == nil {
		return
	}
	a.onTaskNextList(status, detail)
}

func (a *ControllerEventSinkAdapter) OnTaskRecognition(ctrl *Controller, status EventStatus, detail NodeRecognitionDetail) {
	if a == nil || a.onTaskRecognition == nil {
		return
	}
	a.onTaskRecognition(status, detail)
}

func (a *ControllerEventSinkAdapter) OnTaskAction(ctrl *Controller, status EventStatus, detail NodeActionDetail) {
	if a == nil || a.onTaskAction == nil {
		return
	}
	a.onTaskAction(status, detail)
}

func (a *ControllerEventSinkAdapter) OnUnknownEvent(ctrl *Controller, msg, detailsJSON string) {
	if a == nil || a.onUnknownEvent == nil {
		return
	}
	a.onUnknownEvent(msg, detailsJSON)
}

// OnResourceLoading registers a callback sink that only handles Resource.Loading events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnResourceLoading(fn func(EventStatus, ResourceLoadingDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onResourceLoading: fn}
	return c.AddSink(sink)
}

// OnControllerAction registers a callback sink that only handles Controller.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnControllerAction(fn func(EventStatus, ControllerActionDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onControllerAction: fn}
	return c.AddSink(sink)
}

// OnTaskerTask registers a callback sink that only handles Tasker.Task events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnTaskerTask(fn func(EventStatus, TaskerTaskDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onTaskerTask: fn}
	return c.AddSink(sink)
}

// OnNodePipelineNode registers a callback sink that only handles Node.PipelineNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnNodePipelineNode(fn func(EventStatus, NodePipelineNodeDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onNodePipelineNode: fn}
	return c.AddSink(sink)
}

// OnNodeRecognitionNode registers a callback sink that only handles Node.RecognitionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnNodeRecognitionNode(fn func(EventStatus, NodeRecognitionNodeDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onNodeRecognitionNode: fn}
	return c.AddSink(sink)
}

// OnNodeActionNode registers a callback sink that only handles Node.ActionNode events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnNodeActionNode(fn func(EventStatus, NodeActionNodeDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onNodeActionNode: fn}
	return c.AddSink(sink)
}

// OnTaskNextList registers a callback sink that only handles Node.NextList events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnTaskNextList(fn func(EventStatus, NodeNextListDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onTaskNextList: fn}
	return c.AddSink(sink)
}

// OnTaskRecognition registers a callback sink that only handles Node.Recognition events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnTaskRecognition(fn func(EventStatus, NodeRecognitionDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onTaskRecognition: fn}
	return c.AddSink(sink)
}

// OnTaskAction registers a callback sink that only handles Node.Action events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnTaskAction(fn func(EventStatus, NodeActionDetail)) int64 {
	sink := &ControllerEventSinkAdapter{onTaskAction: fn}
	return c.AddSink(sink)
}

// OnUnknownEvent registers a callback sink that only handles unknown events and returns the sink ID.
// The sink ID can be used to remove the sink later.
func (c *Controller) OnUnknownEvent(fn func(msg, detailsJSON string)) int64 {
	sink := &ControllerEventSinkAdapter{onUnknownEvent: fn}
	return c.AddSink(sink)
}
