// Code generated by go generate; DO NOT EDIT.

package maa

type TaskerEventSink interface {
	OnResourceLoading(handle *Tasker, event EventType, detail ResourceLoadingDetail)
	OnControllerAction(handle *Tasker, event EventType, detail ControllerActionDetail)
	OnTaskerTask(handle *Tasker, event EventType, detail TaskerTaskDetail)
	OnNodePipelineNode(handle *Tasker, event EventType, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(handle *Tasker, event EventType, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(handle *Tasker, event EventType, detail NodeActionNodeDetail)
	OnTaskNextList(handle *Tasker, event EventType, detail NodeNextListDetail)
	OnTaskRecognition(handle *Tasker, event EventType, detail NodeRecognitionDetail)
	OnTaskAction(handle *Tasker, event EventType, detail NodeActionDetail)
	OnUnknownNotification(handle *Tasker, msg, detailsJSON string)
}

type ResourceEventSink interface {
	OnResourceLoading(handle *Resource, event EventType, detail ResourceLoadingDetail)
	OnControllerAction(handle *Resource, event EventType, detail ControllerActionDetail)
	OnTaskerTask(handle *Resource, event EventType, detail TaskerTaskDetail)
	OnNodePipelineNode(handle *Resource, event EventType, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(handle *Resource, event EventType, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(handle *Resource, event EventType, detail NodeActionNodeDetail)
	OnTaskNextList(handle *Resource, event EventType, detail NodeNextListDetail)
	OnTaskRecognition(handle *Resource, event EventType, detail NodeRecognitionDetail)
	OnTaskAction(handle *Resource, event EventType, detail NodeActionDetail)
	OnUnknownNotification(handle *Resource, msg, detailsJSON string)
}

type ContextEventSink interface {
	OnResourceLoading(handle *Context, event EventType, detail ResourceLoadingDetail)
	OnControllerAction(handle *Context, event EventType, detail ControllerActionDetail)
	OnTaskerTask(handle *Context, event EventType, detail TaskerTaskDetail)
	OnNodePipelineNode(handle *Context, event EventType, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(handle *Context, event EventType, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(handle *Context, event EventType, detail NodeActionNodeDetail)
	OnTaskNextList(handle *Context, event EventType, detail NodeNextListDetail)
	OnTaskRecognition(handle *Context, event EventType, detail NodeRecognitionDetail)
	OnTaskAction(handle *Context, event EventType, detail NodeActionDetail)
	OnUnknownNotification(handle *Context, msg, detailsJSON string)
}

type ControllerEventSink interface {
	OnResourceLoading(handle Controller, event EventType, detail ResourceLoadingDetail)
	OnControllerAction(handle Controller, event EventType, detail ControllerActionDetail)
	OnTaskerTask(handle Controller, event EventType, detail TaskerTaskDetail)
	OnNodePipelineNode(handle Controller, event EventType, detail NodePipelineNodeDetail)
	OnNodeRecognitionNode(handle Controller, event EventType, detail NodeRecognitionNodeDetail)
	OnNodeActionNode(handle Controller, event EventType, detail NodeActionNodeDetail)
	OnTaskNextList(handle Controller, event EventType, detail NodeNextListDetail)
	OnTaskRecognition(handle Controller, event EventType, detail NodeRecognitionDetail)
	OnTaskAction(handle Controller, event EventType, detail NodeActionDetail)
	OnUnknownNotification(handle Controller, msg, detailsJSON string)
}
