name: release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  meta:
    uses: ./.github/workflows/meta.yml

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: meta
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.meta.outputs.tag }}